### ISSUE TITLE
Changing URL based on props - key needed

### ISSUE THREAD

**Issue by adrianleewt** [robertov8/google-classroom-share#1]
Hey, thanks for making this! While using this and dynamically changing the URL passed into the component, I realized it wasn't initially changing the URL being sent to google classroom. Adding a unique `key` prop into the component fixed it - may be worth putting into the readme.

**Comment by robertov8** [comment]
Hello, I chose to create the update within the component based on the past props, but thanks for letting me know and I created a demo screen.

https://github.com/robertov8/google-classroom-share/commit/50835e41153892c216b07fd5157a1f9816c25786
